import PptxGenJS from 'pptxgenjs';
import { PresentationData } from '../types';

/**
 * Creates a basic text-based PPTX (fallback method).
 */
export const createPptx = (data: PresentationData) => {
  const pptx = new PptxGenJS();
  pptx.author = 'CommitToSlides';
  pptx.company = 'Generated by Gemini';
  pptx.title = data.title;
  pptx.layout = 'LAYOUT_16x9';

  data.slides.forEach((s) => {
    const slide = pptx.addSlide();
    const content = s.pptxContent;
    
    slide.addNotes(s.speakerNotes);
    slide.background = { color: 'FFFFFF' };

    slide.addText(content.title, {
        x: 0.5, y: 0.5, w: '90%', h: 0.8,
        fontSize: 32, bold: true, color: '6750A4',
        fontFace: 'Arial'
    });
    slide.addShape('line', {
        x: 0.5, y: 1.3, w: '90%', h: 0,
        line: { color: 'E7E0EC', width: 2 }
    });

    if (content.mainPoint) {
        slide.addText(content.mainPoint, {
            x: 0.5, y: 1.5, w: '90%', h: 1,
            fontSize: 18, color: '49454F',
            italic: true
        });
    }

    if (content.bullets && content.bullets.length > 0) {
        slide.addText(content.bullets.map(b => `• ${b}`).join('\n'), {
            x: 0.5, y: 2.6, w: '50%', h: 4.5,
            fontSize: 16, color: '1D1B20',
            valign: 'top'
        });
    }

    if (content.codeBlock) {
        const codeX = (content.bullets && content.bullets.length > 0) ? 5.5 : 0.5;
        const codeW = (content.bullets && content.bullets.length > 0) ? '45%' : '90%';

        slide.addShape('rect', {
            x: codeX, y: 2.6, w: codeW, h: 4.5,
            fill: { color: 'F5F5F5' },
            line: { color: 'CCCCCC' }
        });
        slide.addText(content.codeBlock, {
            x: codeX + 0.1, y: 2.7, w: parseFloat(codeW as string) - 0.2, h: 4.3,
            fontSize: 10, fontFace: 'Courier New', color: '333333',
            valign: 'top'
        });
    }
  });

  return pptx;
};

/**
 * Creates a high-fidelity PPTX using screenshots of the DOM.
 */
export const createPptxFromImages = (
    slides: { dataUrl: string, notes: string }[], 
    title: string
) => {
    const pptx = new PptxGenJS();
    
    // Meta
    pptx.author = 'CommitToSlides';
    pptx.company = 'Generated by Gemini';
    pptx.title = title;
    pptx.layout = 'LAYOUT_16x9';

    slides.forEach(s => {
        const slide = pptx.addSlide();
        // Add the screenshot as the background image covers the whole slide
        slide.addImage({ 
            data: s.dataUrl, 
            x: 0, y: 0, w: '100%', h: '100%',
            sizing: { type: 'contain', w: '100%', h: '100%' }
        });
        slide.addNotes(s.notes);
    });

    return pptx;
};