import React from 'react';
import { PresentationSlide } from '../types';

interface SlidePreviewProps {
  slide: PresentationSlide;
  index: number;
  variant?: 'full' | 'thumbnail';
}

const SlidePreview: React.FC<SlidePreviewProps> = ({ 
  slide, 
  variant = 'full',
}) => {
  const isThumbnail = variant === 'thumbnail';
  
  return (
    <div 
      className="w-full h-full bg-white text-slate-900 font-sans overflow-hidden relative"
    >
      {/* 
        We use a transform scale for thumbnails because the HTML generated by Gemini 
        is designed for a full 16:9 viewport (e.g. 1920x1080 or similar relative sizing).
        Tailwind classes like 'text-4xl' will be too big for a thumbnail div otherwise.
      */}
      <div 
        className={`${isThumbnail ? 'origin-top-left absolute inset-0' : 'h-full w-full'}`}
        style={isThumbnail ? { width: '400%', height: '400%', transform: 'scale(0.25)' } : {}}
      >
          {/* 
              SAFE RENDER: The HTML comes from Gemini which is instructed to produce UI code. 
              We trust the sanitized output from the LLM for this specific use case context.
          */}
          <div 
             className="h-full w-full"
             dangerouslySetInnerHTML={{ __html: slide.htmlContent }} 
          />
      </div>
      
      {/* Overlay for thumbnail interaction prevention */}
      {isThumbnail && <div className="absolute inset-0 bg-transparent z-10" />}
    </div>
  );
};

export default SlidePreview;